---
#______________________________________
# set cvmfs configuration files using j2 templates

- name: download repository public key from github
  get_url:
    url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/cvmfs_server_config_files/{{ refdata_cvmfs_repository_name }}.conf'
    dest: '/etc/cvmfs/config.d'
  when: refdata_cvmfs_repository_name != "data.galaxyproject.org"

- name: set cvmfs configuration files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
  when: refdata_cvmfs_repository_name != "data.galaxyproject.org"

#______________________________________
# download the required key.pub of the selected repository from github
# and paste it in the cvmfs key directory

- name: download repository public key from github
  get_url:
    url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/cvmfs_server_keys/{{ refdata_cvmfs_repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ refdata_cvmfs_repository_name }}.pub'
  when: refdata_cvmfs_repository_name != "data.galaxyproject.org"

#_____________________________________
#modification of galaxy.yml file to be mounted in the docker

- name: set test no galaxy.yml
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
          #    - { template: galaxy.yml.j2, dest: /etc/galaxy/galaxy.yml }
    - { template: mygalaxyenv.j2, dest: /etc/galaxy/.mygalaxyenv }
    - { template: delete_galaxy_user.py.j2, dest: /etc/galaxy/delete_galaxy_user.py } 
