---

#______________________________________
# run galaxy docker mounting /export dir and cvmfs config files
# both for ansible version >2.4 and <2.4

- name: "galaxy docker run :TASK specific for ansible >2.4"
  docker_container:
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/etc/galaxy/delete_galaxy_user.py:rw"
      - "/etc/galaxy/galaxy.yml:/etc/galaxy/galaxy.yml:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
      - "/etc/cvmfs/keys/{{ repository_name }}.pub:/etc/cvmfs/keys/{{ repository_name }}.pub:rw"
      - "/etc/cvmfs/default.local:/etc/cvmfs/default.local:rw"
      - "/etc/cvmfs/config.d:/etc/cvmfs/config.d:rw"
      - "/etc/galaxy/tool_data_tables:/etc/galaxy/tool_data_tables:rw"
  when: ansible_version.full >= "2.4.0.0"

- name: "installation of docker-py and galaxy docker run :TASK specific for ansible <2.4"
  docker: 
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/etc/galaxy/delete_galaxy_user.py:rw"
      - "/etc/galaxy/galaxy.yml:/etc/galaxy/galaxy.yml:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
      - "/etc/cvmfs/keys/{{ repository_name }}.pub:/etc/cvmfs/keys/{{ repository_name }}.pub:rw"
      - "/etc/cvmfs/default.local:/etc/cvmfs/default.local:rw"
      - "/etc/cvmfs/config.d:/etc/cvmfs/config.d:rw"
      - "/etc/galaxy/tool_data_tables:/etc/galaxy/tool_data_tables:rw"
  when: ansible_version.full < "2.4.0.0"
